### ISSUE TITLE
Does not build to public

### ISSUE THREAD

**Issue by DanielLvovsky** [kremalicious/portfolio#372]
When ever I run  the command "npm run build" it gives me an error.

Is there any possible fix for this?

**Comment by kremalicious** [comment]
well, what's the error?

**Comment by DanielLvovsky** [comment]
Sorry that I didn't provide the error here is what it gave me:

 
![Annotation 2020-09-02 065918](https://user-images.githubusercontent.com/54752143/91993142-e020c300-ece9-11ea-9b36-2aa366600647.png)

**Comment by kremalicious** [comment]
right, this should be the GitHub fetching in `gatsby-node.js` This requires a `GATSBY_GITHUB_TOKEN` in your `.env` file: https://github.com/kremalicious/portfolio/blob/main/.env.example

Indeed not developer-friendly, should add a warning or simply skip GitHub fetching when no token is found
