### ISSUE TITLE
Misplacement of <p> tag "not available for new projects"

### ISSUE THREAD

**Issue by RiqueBR** [kremalicious/portfolio#97]
Hi! 
The <p> tag "not available for new projects is being rendered in front of the social media icons.

**Comment by kremalicious** [comment]
cool, thanks! That placement with absolute positioning was always a bit weird so revisited and changed in db7cac9649e42b1ee24a703db3c1d1a495c84bf9

**Comment by RiqueBR** [comment]
Awesome! Love this portfolio by the way! Great Job!
